# https://taskfile.dev

version: '3'

includes:
  utils:  ./.tasks/{{OS}}/utils.yml
  branch: ./.tasks/{{OS}}/branch.yml
  app: ./.tasks/{{OS}}/app.yml

tasks:
  setup:
    desc: Setup the project for development
    cmds:
      - task: utils:confirmGit
      - task: utils:installGitHooks
    silent: true

  default:
    cmds:
      - task -l
    silent: true
